dist: trusty

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
addons:
  chrome: stable

before_install:
  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
  #- echo "extension=zip.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php --ini

#  - google-chrome-stable --headless --disable-gpu
#  #--remote-debugging-port=9222 http://localhost &
#  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``

#env:
#  - CI_JOB=lint_syntax
#  - CI_JOB=build_test
#  - CI_JOB=lint_style

#matrix:
#  exclude:
#    - php: '7.2'
#      #env: CI_JOB=lint_style
#    - php: '7.3'
#      #env: CI_JOB=lint_style

script:
  - composer install
  - php vendor/bin/phpunit
